export const INIT_FETCH_GET_DATA = 'INIT_FETCH_GET_DATA';
export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHED_DATA = 'FETCHED_DATA';
export const DATA_FETCHED_COMPLETED = 'DATA_FETCHED_COMPLETED';
