export const INIT_FETCH_GET_DATA = 'INIT_FETCH_GET_DATA';
export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHED_DATA = 'FETCHED_DATA';
export const DATA_FETCHED_COMPLETED = 'DATA_FETCHED_COMPLETED';


export const SELECTED_YEAR_ACTION = 'SELECTED_YEAR_ACTION';
export const SELECTED_LAUNCH_SUCCESS_ACTION = 'SELECTED_LAUNCH_SUCCESS_ACTION';
export const SELECTED_LANDED_SUCCESS_ACTION = 'SELECTED_LANDED_SUCCESS_ACTION';



